interface LookbookStampProps {
  /**
   * Left side — typically location coordinates from
   * `lookbook_settings.stamp_left_nl/en`. Hidden when blank.
   */
  leftText: string
  /**
   * Right side — auto-generated by the parent. Format:
   *   "{nextLabel} — {currentIndex + 1} / {total} · {nextTitle}"
   * e.g. "NEXT — 02 / 04 · LIGHT AS SPRING."
   */
  rightText: string
  /** Flips the colour scheme so the stamp keeps contrast against
   *  whatever chapter sits directly above it. */
  inverted?: boolean
  ariaLabel?: string
}

/**
 * Editorial location/issue stamp shown between lookbook chapters.
 *
 * Inspired by high-end fashion magazines (Acne Paper, Cereal,
 * Kinfolk): a hairline ruling that sits quietly between two chapters
 * with two short text stamps anchoring it. No black slab, no marketing
 * claims, no animation — just a beat of breathing space that carries
 * editorial information instead of selling.
 *
 * Layout
 * - Desktop: `LEFT  ─────────  RIGHT` on a single row.
 * - Mobile:  stacked centred (LEFT / hairline / RIGHT) so the strings
 *   never have to truncate or shrink to illegible sizes.
 *
 * The component is themed (white-on-black or black-on-white) by the
 * caller via `inverted`, mirroring the surrounding chapter's layout
 * variant so dark-chapter transitions still feel cohesive.
 */
export default function LookbookStamp({
  leftText,
  rightText,
  inverted = false,
  ariaLabel,
}: LookbookStampProps) {
  const hasLeft = !!leftText?.trim()
  const hasRight = !!rightText?.trim()
  if (!hasLeft && !hasRight) return null

  const theme = inverted
    ? 'bg-black text-white'
    : 'bg-white text-black'
  const lineColor = inverted ? 'bg-white/30' : 'bg-black/20'
  const borderColor = inverted ? 'border-white' : 'border-black'

  return (
    <section
      className={`${theme} border-y-2 ${borderColor}`}
      aria-label={ariaLabel}
    >
      <div className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8 py-6 md:py-8">
        {/* Desktop / tablet: one-row layout — left text, hairline, right text */}
        <div className="hidden md:flex items-center gap-4 lg:gap-6">
          {hasLeft && (
            <p className="font-display uppercase tracking-[0.3em] text-[11px] lg:text-xs whitespace-nowrap">
              {leftText}
            </p>
          )}
          <span
            aria-hidden="true"
            className={`flex-1 h-px ${lineColor}`}
          />
          {hasRight && (
            <p className="font-display uppercase tracking-[0.3em] text-[11px] lg:text-xs whitespace-nowrap">
              {rightText}
            </p>
          )}
        </div>

        {/* Mobile: stacked + centred so we never have to ellipsis the title */}
        <div className="flex md:hidden flex-col items-center gap-3 text-center">
          {hasLeft && (
            <p className="font-display uppercase tracking-[0.25em] text-[10px] leading-snug">
              {leftText}
            </p>
          )}
          <span
            aria-hidden="true"
            className={`block w-10 h-px ${lineColor}`}
          />
          {hasRight && (
            <p className="font-display uppercase tracking-[0.25em] text-[10px] leading-snug">
              {rightText}
            </p>
          )}
        </div>
      </div>
    </section>
  )
}
