#!/bin/bash

echo "======================================"
echo "🔍 SETTINGS PAGINA DIAGNOSE"
echo "======================================"
echo ""

echo "📋 STAP 1: Database Keys Controleren"
echo "Run deze SQL in Supabase om te checken welke keys er zijn:"
echo ""
echo "SELECT key, value, description FROM site_settings ORDER BY key;"
echo ""
echo "✅ Verwachte keys:"
echo "  - contact_email"
echo "  - currency"
echo "  - free_shipping_threshold (niet shipping_free_threshold!)"
echo "  - low_stock_threshold"
echo "  - maintenance_mode"
echo "  - shipping_cost"
echo "  - site_name"
echo "  - tax_rate"
echo ""

echo "📋 STAP 2: Migratie Uitvoeren"
echo "Als de keys niet kloppen, run de migratie:"
echo ""
cat supabase/migrations/20260103150000_fix_site_settings_keys.sql
echo ""

echo "======================================"
echo "📋 STAP 3: Test Settings op Website"
echo "======================================"
echo ""
echo "1. Ga naar /admin/settings"
echo "2. Pas een instelling aan (bijv. gratis verzending van 100 naar 75)"
echo "3. Klik 'Instellingen Opslaan'"
echo "4. Check of je een ✅ melding ziet"
echo "5. Refresh de pagina - check of de waarde behouden blijft"
echo ""

echo "======================================"
echo "📋 STAP 4: Test of Settings Werken in CartDrawer"
echo "======================================"
echo ""
echo "1. Voeg producten toe aan winkelwagen (totaal < drempel)"
echo "2. Open cart drawer (rechts boven)"
echo "3. Check of je de 'nog €X tot gratis verzending' balk ziet"
echo "4. Check of het bedrag klopt met je ingestelde drempel"
echo "5. Voeg meer producten toe tot boven de drempel"
echo "6. Check of 'Gratis verzending!' verschijnt"
echo ""

echo "======================================"
echo "📋 STAP 5: Test Settings in Checkout"
echo "======================================"
echo ""
echo "1. Ga naar checkout"
echo "2. Check of verzendkosten correct zijn (€0,01 of wat je instelde)"
echo "3. Check of gratis verzending werkt boven drempel"
echo "4. Check of BTW percentage klopt (21%)"
echo ""

echo "======================================"
echo "📋 STAP 6: Cache Test"
echo "======================================"
echo ""
echo "1. Verander een setting in admin (bijv. verzendkosten)"
echo "2. Sla op"
echo "3. Ga DIRECT naar de shop (zonder refresh)"
echo "4. Voeg iets toe aan cart"
echo "5. Check of de NIEUWE verzendkosten worden gebruikt"
echo "6. Als het de oude kosten toont, is de cache niet gecleared"
echo ""

echo "======================================"
echo "🔧 BEVINDINGEN & FIXES"
echo "======================================"
echo ""
echo "Als settings NIET werken:"
echo ""
echo "PROBLEEM 1: Keys kloppen niet in database"
echo "FIX: Run de migratie hierboven (stap 2)"
echo ""
echo "PROBLEEM 2: Settings worden wel opgeslagen maar niet gebruikt"
echo "FIX: Check of getSiteSettings() wordt aangeroepen in de component"
echo ""
echo "PROBLEEM 3: Cache wordt niet gecleared"
echo "FIX: clearSettingsCache() wordt aangeroepen in handleSaveSettings()"
echo ""
echo "PROBLEEM 4: Settings werken lokaal maar niet op Vercel"
echo "FIX: Check Supabase connection en RLS policies"
echo ""

echo "======================================"
echo "📊 CODE REVIEW CHECKLIST"
echo "======================================"
echo ""
echo "✅ CartDrawer.tsx gebruikt getSiteSettings() in useEffect"
echo "✅ Checkout page gebruikt getSiteSettings() in useEffect"
echo "✅ API route gebruikt await getSiteSettings()"
echo "✅ Settings pagina roept clearSettingsCache() aan na opslaan"
echo "✅ Database tabel heeft correcte key names"
echo "✅ RLS policies staan admin access toe"
echo ""


